
version: '3.8'

services:
  authentication:
    image: jorgfernvi/authentication-api-cloud:latest
    ports:
      - "8001:8001"
    networks:
      - mynetwork

  accounts:
    image: jorgfernvi/accounts-api-cloud:latest
    ports:
      - "8002:8002"
    networks:
      - mynetwork

  transactions:
    image: jorgfernvi/transactions-api-cloud:latest
    ports:
      - "8003:8003"
    networks:
      - mynetwork

  cards:
    image: jorgfernvi/cards-api-cloud:latest
    ports:
      - "8004:8004"
    networks:
      - mynetwork

  loans:
    image: jorgfernvi/loans-api-cloud:latest
    ports:
      - "8005:8005"
    networks:
      - mynetwork

  notifications:
    image: jorgfernvi/notifications-api-cloud:latest
    ports:
      - "8006:8006"
    networks:
      - mynetwork

  reports:
    image: jorgfernvi/reports-api-cloud:latest
    ports:
      - "8007:8007"
    networks:
      - mynetwork

  swagger-catalog:
    image: jorgfernvi/swagger-catalog:latest
    ports:
      - "8080:8080"
    volumes:
      - ./catalog:/usr/share/nginx/html/catalog
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
