openapi: 3.0.0
info:
  title: Notification Service API
  version: 1.0.0
  description: API for managing user notifications

paths:
  /notifications:
    post:
      summary: Create Notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: Notification created successfully

  /notifications/{user_id}:
    get:
      summary: Get User Notifications
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: integer
                  notifications:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'

  /notifications/{notification_id}/read:
    put:
      summary: Mark Notification as Read
      parameters:
        - in: path
          name: notification_id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Notification marked as read

components:
  schemas:
    Notification:
      type: object
      properties:
        user_id:
          type: integer
        message:
          type: string

