openapi: 3.0.0
info:
  title: API de Informes Financieros
  version: 1.0.0
  description: API para informes financieros basados en transacciones

servers:
  - url: http://44.218.163.17:8005

paths:
  /expenses:
    get:
      summary: Obtener informe de gastos
      parameters:
        - in: query
          name: user_id
          required: true
          description: ID del usuario
          schema:
            type: integer
        - in: query
          name: category
          required: false
          description: Categoría de gastos
          schema:
            type: string
      responses:
        '200':
          description: Informe de gastos obtenido correctamente

  /income:
    get:
      summary: Obtener informe de ingresos
      parameters:
        - in: query
          name: user_id
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Informe de ingresos obtenido correctamente

  /financial-analysis:
    get:
      summary: Obtener análisis financiero
      parameters:
        - in: query
          name: user_id
          required: true
          description: ID del usuario
          schema:
            type: integer
      responses:
        '200':
          description: Análisis financiero obtenido correctamente

  /transactions:
    post:
      summary: Crear transacción
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transacción creada correctamente

  /transactions/{transaction_id}:
    put:
      summary: Actualizar transacción
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: ID de la transacción a actualizar
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Transaction'
      responses:
        '200':
          description: Transacción actualizada correctamente
        '404':
          description: Transacción no encontrada

    delete:
      summary: Eliminar transacción
      parameters:
        - in: path
          name: transaction_id
          required: true
          description: ID de la transacción a eliminar
          schema:
            type: integer
      responses:
        '200':
          description: Transacción eliminada correctamente
        '404':
          description: Transacción no encontrada

components:
  schemas:
    Transaction:
      type: object
      properties:
        user_id:
          type: integer
        amount:
          type: number
        transaction_type:
          type: string
        category:
          type: string

